Feature/GitHub to gitlab
Sysvale/cookiecutter-pypackage pull request #21
Opened 2020-06-05 19:37 UTC by elaynelemos

Change github references to gitlab ones.

2020-06-08 14:39 UTC, denissonleal commented
@elaynelemos apareceu um conflito

2020-06-08 17:07 UTC, denissonleal requested changes

2020-06-08 17:07 UTC, denissonleal commented on {{cookiecutter.project_slug}}/readme.md
> +<<<<<<< HEAD
hey, isso aqui é de um conflito

2020-06-08 17:35 UTC, elaynelemos commented on {{cookiecutter.project_slug}}/readme.md
> +<<<<<<< HEAD
Eu corrigi em 8355301 e corrigi referências em 190ba1a.

2020-06-08 17:51 UTC, denissonleal approved these changes

2020-06-10 18:40 UTC, LEMSantos approved these changes

2020-06-10 19:18 UTC, merged